<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="8" total="17" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="test1" duration-ms="170984" started-at="2014-08-13T03:09:03Z" finished-at="2014-08-13T03:11:54Z">
    <groups>
    </groups>
    <test name="test1_1" duration-ms="23334" started-at="2014-08-13T03:09:03Z" finished-at="2014-08-13T03:09:27Z">
      <class name="com.sample.test1.Test1_1">
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.Test1_1@29db197]" name="checktestcaserunnable" is-config="true" duration-ms="6" started-at="2014-08-13T08:39:03Z" finished-at="2014-08-13T08:39:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.sample.test1.Test1_1@29db197]" name="test1" duration-ms="23311" started-at="2014-08-13T08:39:03Z" finished-at="2014-08-13T08:39:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.sample.test1.Test1_1 -->
    </test> <!-- test1_1 -->
    <test name="brand_search" duration-ms="8639" started-at="2014-08-13T03:09:27Z" finished-at="2014-08-13T03:09:35Z">
      <class name="com.sample.test1.brandsearch">
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="checktestcaserunnable" is-config="true" duration-ms="5" started-at="2014-08-13T08:39:27Z" finished-at="2014-08-13T08:39:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="FAIL" signature="test2in1(java.lang.String)[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="test2in1" duration-ms="3328" started-at="2014-08-13T08:39:27Z" data-provider="getTestData" finished-at="2014-08-13T08:39:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.sample.test1.brandsearch.test2in1(brandsearch.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2in1 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="setresultforData" is-config="true" duration-ms="1975" started-at="2014-08-13T08:39:30Z" finished-at="2014-08-13T08:39:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="checktestcaserunnable" is-config="true" duration-ms="4" started-at="2014-08-13T08:39:32Z" finished-at="2014-08-13T08:39:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="FAIL" signature="test2in1(java.lang.String)[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="test2in1" duration-ms="651" started-at="2014-08-13T08:39:32Z" data-provider="getTestData" finished-at="2014-08-13T08:39:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.sample.test1.brandsearch.test2in1(brandsearch.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2in1 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="setresultforData" is-config="true" duration-ms="142" started-at="2014-08-13T08:39:33Z" finished-at="2014-08-13T08:39:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="checktestcaserunnable" is-config="true" duration-ms="4" started-at="2014-08-13T08:39:33Z" finished-at="2014-08-13T08:39:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="FAIL" signature="test2in1(java.lang.String)[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="test2in1" duration-ms="619" started-at="2014-08-13T08:39:33Z" data-provider="getTestData" finished-at="2014-08-13T08:39:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.sample.test1.brandsearch.test2in1(brandsearch.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2in1 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="setresultforData" is-config="true" duration-ms="215" started-at="2014-08-13T08:39:33Z" finished-at="2014-08-13T08:39:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="checktestcaserunnable" is-config="true" duration-ms="4" started-at="2014-08-13T08:39:34Z" finished-at="2014-08-13T08:39:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="FAIL" signature="test2in1(java.lang.String)[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="test2in1" duration-ms="657" started-at="2014-08-13T08:39:34Z" data-provider="getTestData" finished-at="2014-08-13T08:39:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.sample.test1.brandsearch.test2in1(brandsearch.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2in1 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="setresultforData" is-config="true" duration-ms="144" started-at="2014-08-13T08:39:34Z" finished-at="2014-08-13T08:39:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="checktestcaserunnable" is-config="true" duration-ms="4" started-at="2014-08-13T08:39:34Z" finished-at="2014-08-13T08:39:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="FAIL" signature="test2in1(java.lang.String)[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="test2in1" duration-ms="675" started-at="2014-08-13T08:39:34Z" data-provider="getTestData" finished-at="2014-08-13T08:39:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Peter]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.sample.test1.brandsearch.test2in1(brandsearch.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2in1 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test1.brandsearch@6647dc79]" name="setresultforData" is-config="true" duration-ms="144" started-at="2014-08-13T08:39:35Z" finished-at="2014-08-13T08:39:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
      </class> <!-- com.sample.test1.brandsearch -->
    </test> <!-- brand_search -->
    <test name="pricefilter" duration-ms="20226" started-at="2014-08-13T03:09:35Z" finished-at="2014-08-13T03:09:56Z">
      <class name="com.sample.test1.pricefilter">
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.pricefilter@5219f360]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:39:35Z" finished-at="2014-08-13T08:39:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="FAIL" signature="price_filter()[pri:0, instance:com.sample.test1.pricefilter@5219f360]" name="price_filter" duration-ms="20223" started-at="2014-08-13T08:39:35Z" finished-at="2014-08-13T08:39:56Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[Unable to locate element: {"method":"xpath","selector":"//*[@id='price_range']/li[0]/a/span"}
Command duration or timeout: 20.16 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Session ID: e350c285-331f-4345-bd8e-f602a1c6c8f8
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=XP, databaseEnabled=true, cssSelectorsEnabled=true, javascriptEnabled=true, acceptSslCerts=true, handlesAlerts=true, browserName=firefox, webStorageEnabled=true, nativeEvents=false, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//*[@id='price_range']/li[0]/a/span"}
Command duration or timeout: 20.16 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Session ID: e350c285-331f-4345-bd8e-f602a1c6c8f8
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=XP, databaseEnabled=true, cssSelectorsEnabled=true, javascriptEnabled=true, acceptSslCerts=true, handlesAlerts=true, browserName=firefox, webStorageEnabled=true, nativeEvents=false, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
	at com.sun.proxy.$Proxy12.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:184)
	at com.sample.test1.pricefilter.price_filter(pricefilter.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Unable to locate element: {"method":"xpath","selector":"//*[@id='price_range']/li[0]/a/span"}
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///C:/Users/Gokul/AppData/Local/Temp/anonymous843220213634677613webdriver-profile/extensions/fxdriver@googlecode.com/components/driver_component.js:9470:133)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/Gokul/AppData/Local/Temp/anonymous843220213634677613webdriver-profile/extensions/fxdriver@googlecode.com/components/driver_component.js:407:5)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- price_filter -->
      </class> <!-- com.sample.test1.pricefilter -->
    </test> <!-- pricefilter -->
    <test name="pricefilter unselection" duration-ms="20180" started-at="2014-08-13T03:09:56Z" finished-at="2014-08-13T03:10:16Z">
      <class name="com.sample.test1.pricefilter_unselection">
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.pricefilter_unselection@2fa1610b]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:39:56Z" finished-at="2014-08-13T08:39:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="FAIL" signature="price_filter_unselection()[pri:0, instance:com.sample.test1.pricefilter_unselection@2fa1610b]" name="price_filter_unselection" duration-ms="20177" started-at="2014-08-13T08:39:56Z" finished-at="2014-08-13T08:40:16Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[Unable to locate element: {"method":"xpath","selector":"//*[@id='selectedFilters']/div/a/span"}
Command duration or timeout: 20.12 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Session ID: e350c285-331f-4345-bd8e-f602a1c6c8f8
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=XP, databaseEnabled=true, cssSelectorsEnabled=true, javascriptEnabled=true, acceptSslCerts=true, handlesAlerts=true, browserName=firefox, webStorageEnabled=true, nativeEvents=false, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//*[@id='selectedFilters']/div/a/span"}
Command duration or timeout: 20.12 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Session ID: e350c285-331f-4345-bd8e-f602a1c6c8f8
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=XP, databaseEnabled=true, cssSelectorsEnabled=true, javascriptEnabled=true, acceptSslCerts=true, handlesAlerts=true, browserName=firefox, webStorageEnabled=true, nativeEvents=false, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
	at com.sun.proxy.$Proxy12.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:184)
	at com.sample.base.TestBase.getobject(TestBase.java:104)
	at com.sample.test1.pricefilter_unselection.price_filter_unselection(pricefilter_unselection.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Unable to locate element: {"method":"xpath","selector":"//*[@id='selectedFilters']/div/a/span"}
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///C:/Users/Gokul/AppData/Local/Temp/anonymous843220213634677613webdriver-profile/extensions/fxdriver@googlecode.com/components/driver_component.js:9470:133)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/Gokul/AppData/Local/Temp/anonymous843220213634677613webdriver-profile/extensions/fxdriver@googlecode.com/components/driver_component.js:407:5)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- price_filter_unselection -->
      </class> <!-- com.sample.test1.pricefilter_unselection -->
    </test> <!-- pricefilter unselection -->
    <test name="brand_selection" duration-ms="15582" started-at="2014-08-13T03:10:16Z" finished-at="2014-08-13T03:10:32Z">
      <class name="com.sample.test1.brandfilter">
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.brandfilter@5d729d49]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:40:16Z" finished-at="2014-08-13T08:40:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="brand_filter()[pri:0, instance:com.sample.test1.brandfilter@5d729d49]" name="brand_filter" duration-ms="15580" started-at="2014-08-13T08:40:16Z" finished-at="2014-08-13T08:40:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- brand_filter -->
      </class> <!-- com.sample.test1.brandfilter -->
    </test> <!-- brand_selection -->
    <test name="brand_unselection" duration-ms="27776" started-at="2014-08-13T03:10:32Z" finished-at="2014-08-13T03:10:59Z">
      <class name="com.sample.test1.brand_unselection">
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.brand_unselection@6f0abf2c]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:40:32Z" finished-at="2014-08-13T08:40:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="brand_unselection()[pri:0, instance:com.sample.test1.brand_unselection@6f0abf2c]" name="brand_unselection" duration-ms="27774" started-at="2014-08-13T08:40:32Z" finished-at="2014-08-13T08:40:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- brand_unselection -->
      </class> <!-- com.sample.test1.brand_unselection -->
    </test> <!-- brand_unselection -->
    <test name="Mixedfilter" duration-ms="54899" started-at="2014-08-13T03:10:59Z" finished-at="2014-08-13T03:11:54Z">
      <class name="com.sample.test1.Mixedfilter">
        <test-method status="PASS" signature="checksuiteskip()[pri:0, instance:com.sample.test1.Mixedfilter@7031086c]" name="checksuiteskip" is-config="true" duration-ms="16521" started-at="2014-08-13T08:38:47Z" finished-at="2014-08-13T08:39:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checksuiteskip -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test1.Mixedfilter@7031086c]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:40:59Z" finished-at="2014-08-13T08:40:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="FAIL" signature="mixed_filter()[pri:0, instance:com.sample.test1.Mixedfilter@7031086c]" name="mixed_filter" duration-ms="54897" started-at="2014-08-13T08:40:59Z" finished-at="2014-08-13T08:41:54Z">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 20.11 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Session ID: e350c285-331f-4345-bd8e-f602a1c6c8f8
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=XP, databaseEnabled=true, cssSelectorsEnabled=true, javascriptEnabled=true, acceptSslCerts=true, handlesAlerts=true, browserName=firefox, webStorageEnabled=true, nativeEvents=false, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 20.11 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Session ID: e350c285-331f-4345-bd8e-f602a1c6c8f8
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=XP, databaseEnabled=true, cssSelectorsEnabled=true, javascriptEnabled=true, acceptSslCerts=true, handlesAlerts=true, browserName=firefox, webStorageEnabled=true, nativeEvents=false, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:152)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:331)
	at com.sun.proxy.$Proxy13.getText(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getText(EventFiringWebDriver.java:381)
	at com.sample.test1.Mixedfilter.mixed_filter(Mixedfilter.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Element not found in the cache - perhaps the page has changed since it was looked up
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'Gokul-VAIO', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web_element_cache.js:8180:5)
	at <anonymous class>.Utils.getElementAt(file:///C:/Users/Gokul/AppData/Local/Temp/anonymous843220213634677613webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:7783:3)
	at <anonymous class>.WebElement.getElementText(file:///C:/Users/Gokul/AppData/Local/Temp/anonymous843220213634677613webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:10893:7)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/Gokul/AppData/Local/Temp/anonymous843220213634677613webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:11455:16)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/Gokul/AppData/Local/Temp/anonymous843220213634677613webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:407:5)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mixed_filter -->
      </class> <!-- com.sample.test1.Mixedfilter -->
    </test> <!-- Mixedfilter -->
  </suite> <!-- test1 -->
  <suite name="My test" duration-ms="0" started-at="2014-08-13T03:11:56Z" finished-at="2014-08-13T03:11:56Z">
    <groups>
    </groups>
  </suite> <!-- My test -->
  <suite name="test2" duration-ms="1381" started-at="2014-08-13T03:11:54Z" finished-at="2014-08-13T03:11:56Z">
    <groups>
    </groups>
    <test name="test2_1" duration-ms="696" started-at="2014-08-13T03:11:54Z" finished-at="2014-08-13T03:11:55Z">
      <class name="com.sample.test2.Test2_1">
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:41:54Z" finished-at="2014-08-13T08:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="test1in2(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="test1in2" duration-ms="1" started-at="2014-08-13T08:41:54Z" data-provider="getTestData" finished-at="2014-08-13T08:41:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dummy2_1_1_1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Dummy2_1_1_2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Dummy2_1_1_3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1in2 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="setresultforData" is-config="true" duration-ms="227" started-at="2014-08-13T08:41:54Z" finished-at="2014-08-13T08:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:41:54Z" finished-at="2014-08-13T08:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="test1in2(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="test1in2" duration-ms="1" started-at="2014-08-13T08:41:54Z" data-provider="getTestData" finished-at="2014-08-13T08:41:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dummy2_1_2_1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Dummy2_1_2_2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Dummy2_1_2_3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1in2 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="setresultforData" is-config="true" duration-ms="113" started-at="2014-08-13T08:41:54Z" finished-at="2014-08-13T08:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="checktestcaserunnable" is-config="true" duration-ms="3" started-at="2014-08-13T08:41:55Z" finished-at="2014-08-13T08:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="test1in2(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="test1in2" duration-ms="0" started-at="2014-08-13T08:41:55Z" data-provider="getTestData" finished-at="2014-08-13T08:41:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dummy2_1_3_1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Dummy2_1_3_2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Dummy2_1_3_3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1in2 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test2.Test2_1@64d74895]" name="setresultforData" is-config="true" duration-ms="343" started-at="2014-08-13T08:41:55Z" finished-at="2014-08-13T08:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
      </class> <!-- com.sample.test2.Test2_1 -->
    </test> <!-- test2_1 -->
    <test name="test2_2" duration-ms="657" started-at="2014-08-13T03:11:55Z" finished-at="2014-08-13T03:11:56Z">
      <class name="com.sample.test2.Test2_2">
        <test-method status="PASS" signature="checksuiteskip()[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="checksuiteskip" is-config="true" duration-ms="0" started-at="2014-08-13T08:41:54Z" finished-at="2014-08-13T08:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checksuiteskip -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:41:55Z" finished-at="2014-08-13T08:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="test2in2(java.lang.String, java.lang.String)[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="test2in2" duration-ms="1" started-at="2014-08-13T08:41:55Z" data-provider="getTestData" finished-at="2014-08-13T08:41:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dummy2_2_1_1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Dummy2_2_1_2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2in2 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="setresultforData" is-config="true" duration-ms="220" started-at="2014-08-13T08:41:55Z" finished-at="2014-08-13T08:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:41:55Z" finished-at="2014-08-13T08:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="test2in2(java.lang.String, java.lang.String)[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="test2in2" duration-ms="1" started-at="2014-08-13T08:41:55Z" data-provider="getTestData" finished-at="2014-08-13T08:41:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dummy2_2_2_1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Dummy2_2_2_2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2in2 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="setresultforData" is-config="true" duration-ms="161" started-at="2014-08-13T08:41:55Z" finished-at="2014-08-13T08:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
        <test-method status="PASS" signature="checktestcaserunnable()[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="checktestcaserunnable" is-config="true" duration-ms="2" started-at="2014-08-13T08:41:55Z" finished-at="2014-08-13T08:41:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktestcaserunnable -->
        <test-method status="PASS" signature="test2in2(java.lang.String, java.lang.String)[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="test2in2" duration-ms="0" started-at="2014-08-13T08:41:55Z" data-provider="getTestData" finished-at="2014-08-13T08:41:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dummy2_2_3_1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Dummy2_2_3_2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2in2 -->
        <test-method status="PASS" signature="setresultforData()[pri:0, instance:com.sample.test2.Test2_2@5ee556a1]" name="setresultforData" is-config="true" duration-ms="266" started-at="2014-08-13T08:41:55Z" finished-at="2014-08-13T08:41:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setresultforData -->
      </class> <!-- com.sample.test2.Test2_2 -->
    </test> <!-- test2_2 -->
  </suite> <!-- test2 -->
</testng-results>
